#ifndef EXAMPLE_CONSTANTVALUES_H
#define EXAMPLE_CONSTANTVALUES_H

const int SCREEN_WIDTH{700};
#define SCREEN_WIDTHMC 800;
#define SCREEN_HEIGHTMC 700;
const int SCREEN_HEIGHT{700};

#endif //EXAMPLE_CONSTANTVALUES_H
